# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# Check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }} -X main.projectName={{ .ProjectName }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
    # Path to main.go file or main package.
    # Default is `.`.
    main: ./cmd/main.go
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?(feat|new|initial|support|introduce)\b.*?:'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?(fix|bug)\b.*?:|.*fixes$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs?(\(.+\))?\b.*?:'
      order: 2
    - title: Dependency Updates
      regexp: '^.*?(build|deps|upgrade|update)(\(.+\))?\b.*?:'
      order: 3
    - title: Other Changes
      regexp: '.*'
      order: 999
  filters:
    exclude:
      - '^wip\b'
      - '^WIP\b'
      - '(?i)^help\b'
      - '(?i)^trying\b'
      - '(?i)^workflow\b'
      - '(?i)^test\b'
      - '(?i)^style\b'
      - '^chore\b'
      - '(?i)update readme'
dockers_v2:
  - images:
      - "jimschubert/delete-artifacts"
    tags:
      - "latest"
      - "{{ .Tag }}"
      # - "v{{ .Major }}"
    dockerfile: release.Dockerfile
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
    build_args:
      APP_NAME: "{{ .ProjectName }}"
