name: Build Go
on:
  push:
    branches: [ 'main', 'master', 'feature/*' ]
    tags: [ 'v*' ]

permissions:
  contents: write
  packages: write
  # id-token is required for attestation (signing)
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  build:
    uses: jimschubert/.workflows/.github/workflows/go-build-goreleaser.yml@main
    with:
      golangci-lint-version: "v2.7.2"
    secrets: inherit

  mirror-to-ghcr:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    uses: jimschubert/.workflows/.github/workflows/docker-mirror.yml@main
    with:
      source-image: jimschubert/delete-artifacts:${{ github.ref_name }}
      target-image: ghcr.io/jimschubert/delete-artifacts/delete-artifacts
    secrets: inherit

